---
title: "Tables"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Univariate
## median and CI
\begin{table}[H]
\centering
\caption{Results from the sensitivity analysis summarized by the median and 95\% confidence intervals for the various simulations considered.}
\vspace{0.5cm}
\begin{adjustbox}{width=1\textwidth}
\begin{tabular}{llllllll}
\hline
Parameter& Days to Eradication& Attack Rate & 
Total Infected & Infected residents &  Infected staff & Hospitalizations & Deaths\\
%------------------------------------------------------------------
\hline 
Baseline & 106.46 (99.9, 112.88)&0.29 (0.26, 0.31)&98.5 (90, 106)&60 (54.5, 65)&38 (35, 41)&25.5 (23, 27.5) & 3 (2.5, 3.5)\\
%-------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Transmission probability}\\
%-------------------------------------------------------------------
Low transmission (0.304)&50.52 (47.52, 53.9)&0.04 (0.04, 0.05)&15 (13.5, 17.5)&11.5 (10, 12.5)&7 (6.5, 8) & 	3.5 (3, 4)&1.5 (1.5, 1.5)\\
Moderate transmission (0.38) & 	60.65 (57.77, 63.63)&0.09 (0.08, 0.1)&31.5 (28, 34.5)&22 (20, 24.5)&13.5 (12, 15)& 8.5 (7.5, 9.5)&2 (2, 2.5)\\
High transmission (0.42)& 	66.79 (64.56, 69.02)&0.16 (0.15, 0.17)&55 (50.5, 59.5)&36 (33, 39)&22 (20.5, 24)& 14.5 (13.5, 16)&3 (2.5, 3)\\
%-------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Introduction probability}\\
%-------------------------------------------------------------------
Low introduction probability(0.01) & 52.25 (48.69, 56.35)&0.06 (0.04, 0.08)&19 (14, 26.5)&20 (16.5, 25.5)&12.5 (8, 16)&3 (2.5, 4)&2.5 (2, 3)\\
Moderate introduction probability(0.05) & 63.29 (60.9, 65.6)&0.09 (0.08, 0.1)&31.5 (29, 34)&21.5 (19.5, 23)&14 (13, 15)& 8.5 (7.5, 9)&2 (2, 2.5)\\
High introduction probability(0.1) & 61.1 (58.87, 63.31)&0.12 (0.11, 0.14)&42.5 (38.5, 47)&29 (26, 32)&16.5 (15.5, 18.5)& 12.5 (11.5, 13.5)&2.5 (2.5, 2.5)\\
%-------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Detection probability}\\
%-------------------------------------------------------------------
Low detection probability(0.64) &67.02 (64.13, 69.87)&0.14 (0.13, 0.15)&48 (44, 53)&33.5 (30.5, 36.5)&19 (17.5, 21)& 	13 (12, 14.5)&2.5 (2.5, 3)\\
Moderate detection probability(0.8) &		66 (63, 68.81)&0.14 (0.12, 0.15)&46.5 (41, 52.5)&31.5 (27.5, 35.5)&20.5 (18.5, 22.5)& 12 (11, 13.5)&2.5 (2.5, 3)\\
High detection probability(0.9) &53.73 (51.4, 56.19)&0.06 (0.05, 0.07)&20.5 (18.5, 22.5)&15 (13.5, 16.5)&9.5 (8.5, 10)&	5.5 (5, 6)&2 (1.5, 2)\\
%-----------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{PPE effect}\\
%-------------------------------------------------------------------
High effect PPE(0.07)& 30.21 (26.04, 35.1)&0.02 (0.01, 0.02)&5.5 (4.5, 6.5)&4 (3, 5.5)&2.5 (2, 3.5)&1.5 (1.5, 2)&	1 (1, 1)\\
Moderate effect PPE(0.14)& 	53.33 (50.04, 56.73)&0.05 (0.05, 0.06)&18 (16, 20)&13.5 (12, 15)&8.5 (7.5, 9)&5 (4.5, 5.5)& 1.5 (1.5, 2)\\
Low effect PPE(0.34)& 66.08 (64.29, 67.83)&0.14 (0.13, 0.15)&46.5 (43, 50)&31.5 (29.5, 34)&19 (18, 20.5)&12.5 (11.5, 13)& 2.5 (2.5, 3)\\
%-----------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Testing frequency}\\
%-------------------------------------------------------------------
Testing frequency, 7-days$^a$& 	96.65 (90.92, 102.33)&0.22 (0.2, 0.24)&75.5 (67.5, 83.5)&47.5 (42.5, 53)&29.5 (26.5, 33)& 	19 (16.5, 21)&2.5 (2.5, 3)\\
Testing frequency, 5-days$^a$ & 73.19 (66.02, 80.69)&0.1 (0.08, 0.11)&33.5 (28, 38)&22.5 (19.5, 25.5)&13.5 (11, 15)&9.5 (8, 10.5)&2 (1.5, 2)\\
Testing Frequency,  3-days$^a$ & 49.85 (42.42, 59.67)&0.05 (0.03, 0.06)&15.5 (11.5, 19.5)&11.5 (9, 14)&6.5 (5, 8)&		4.5 (3.5, 5)&1.5 (1, 1.5)\\
%------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Vaccine effect}\\
%-------------------------------------------------------------------
Similar age-specific vaccine efficacy & 62.27 (59.48, 65.08)&0.09 (0.08, 0.1)&32 (29, 36)&22.5 (20, 25)&14 (12.5, 15.5)&8.5 (7.5, 9.5)&2.5 (2, 2.5)\\
Different age-specific vaccine efficacy [Pfizer] & 	58.73 (55.81, 61.58)&0.1 (0.08, 0.11)&33 (29, 36.5)&23.5 (21, 26)&14 (12.5, 15.5)&9 (8, 10)& 2.5 (2, 2.5)\\
Different age-specific vaccine efficacy [Moderna] & 	60.83 (57.96, 63.73)&0.1 (0.09, 0.11)&35 (31.5, 38.5)&24.5 (22, 27)&16 (14.5, 17.5)&9 (8, 10)&2 (2, 2.5)\\
%-----------------------------------------------------------------
\hline
\end{tabular}
\end{adjustbox}
\label{tab:Table2}
\footnotesize{$^b$ Vaccine assumed for resident agents, $^c$ Vaccine assumed for staff agents}
\end{table}


## Difference

\begin{table}[H]
\centering
\caption{Results from the sensitivity analysis summarized by the median and 95\% confidence intervals for the various simulations considered.}
\vspace{0.5cm}
\begin{adjustbox}{width=1\textwidth}
\begin{tabular}{llllllll}
\hline
Parameter& Days to Eradication& Attack Rate & 
Total Infected & Infected residents &  Infected staff & Hospitalizations & Deaths\\
%------------------------------------------------------------------
\hline 
Baseline & 106.46 (99.9, 112.88)&0.29 (0.26, 0.31)&98.5 (90, 106)&60 (54.5, 65)&38 (35, 41)&25.5 (23, 27.5) & 3 (2.5, 3.5)\\
%-------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Transmission probability}\\
%-------------------------------------------------------------------
Low transmission (0.304)& -19.96(-26.68,-13.24)$^*$ & -0.12(-0.16,-0.09)$^*$ & -42.73(-53.82,-31.65)$^*$ & -26.06(-32.8,-19.31)$^*$ & -16.68(-21.12,-12.23)$^*$ & -10.79(-13.68,-7.9)$^*$ & -1.38(-1.79,-0.97)$^*$\\
High transmission (0.42)& 9.81(2.95,16.68)$^*$ & 0.11(0.07,0.14)$^*$ & 36.4(25.08,47.71)$^*$ & 21.83(14.94,28.71)$^*$ & 14.57(10.03,19.11)$^*$ & 9.27(6.32,12.22)$^*$ & 1.13(0.72,1.55)$^*$\\
%-------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Introduction probability}\\
%-------------------------------------------------------------------
Low introduction probability(0.01) &,-26.82(-33.71,-19.93)$^*$ & 0(-0.04,0.03)$^*$ & -0.28(-12.44,11.89)$^*$ & -3.34(-10.66,3.99)$^*$ & 3.06(-1.85,7.97)$^*$ & -1.56(-4.69,1.57)$^*$ & -0.22(-0.65,0.22)$^*$\\
High introduction probability(0.1) & 3.38(-3.7,10.47)$^*$ & 0.11(0.07,0.14)$^*$ & 37.29(24.78,49.81)$^*$ & 26.52(18.98,34.06)$^*$ & 10.78(5.72,15.83)$^*$ & 11.28(8.06,14.5)$^*$ & 1.41(0.96,1.86)$^*$\\
%-------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Detection probability}\\
%-------------------------------------------------------------------
Low detection probability(0.64) &10.16(1.68,18.64)$^*$ & 0.03(-0.01,0.07)$^*$ & 10.81(-3.15,24.78)$^*$ & 7.9(-0.54,16.34)$^*$ & 2.92(-2.75,8.58)$^*$ & 3.54(-0.09,7.17)$^*$ & 0.3(-0.23,0.82)$^*$\\
High detection probability(0.9) &-23.49(-30.17,-16.82)$^*$ & -0.19(-0.22,-0.16)$^*$ & -65.23(-76.23,-54.23)$^*$ & -40.11(-46.76,-33.47)$^*$ & -25.12(-29.58,-20.66)$^*$ & -16.49(-19.35,-13.63)$^*$ & -1.86(-2.27,-1.45)$^*$\\
%-----------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{PPE effect}\\
%-------------------------------------------------------------------
High effect PPE(0.07)&-41.73(-52.31,-31.14)$^*$ & -0.09(-0.13,-0.04)$^*$ & -29.24(-46.43,-12.05)$^*$ & -17.58(-27.98,-7.17)$^*$ & -11.66(-18.63,-4.7)$^*$ & -7.14(-11.62,-2.66)$^*$ & -1.03(-1.68,-0.37)$^*$\\
Low effect PPE(0.34)&22.13(16.63,27.63)$^*$ & 0.22(0.19,0.24)$^*$ & 75.13(66.2,84.06)$^*$ & 46.32(40.91,51.72)$^*$ & 28.82(25.2,32.43)$^*$ & 19.35(17.02,21.68)$^*$ & 2.21(1.87,2.55)$^*$\\
%-----------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Testing frequency}\\
%-------------------------------------------------------------------
Testing frequency, 5-days$^a$ & -26.98(-36.51,-17.44)$^*$ & -0.12(-0.14,-0.1)$^*$ & -41.68(-49.52,-33.84)$^*$ & -24.85(-29.75,-19.95)$^*$ & -16.83(-19.89,-13.77)$^*$ & -9.94(-12.16,-7.72)$^*$ & -1.18(-1.55,-0.82)$^*$\\
Testing Frequency,  3-days$^a$-48.53(-58.31,-38.76)$^*$ & -0.17(-0.19,-0.14)$^*$ & -57.33(-65.37,-49.29)$^*$ & -34.57(-39.59,-29.55)$^*$ & -22.76(-25.9,-19.62)$^*$ & -14.59(-16.86,-12.31)$^*$ & -1.71(-2.08,-1.34)$^*$\\
%------------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Vaccine distribution (when compared to no vaccination)}\\
%-------------------------------------------------------------------
Equal distribution & -38.89(-42.38,-35.4)$^*$ & -0.16(-0.17,-0.14)$^*$ & -53.66(-58.48,-48.85)$^*$ & -33.29(-36.21,-30.36)$^*$ & -20.37(-22.34,-18.41)$^*$ & -13.76(-15.01,-12.5)$^*$ & -1.65(-1.82,-1.47)$^*$\\
Resident Priority & -34.08(-37.67,-30.48)$^*$ & -0.15(-0.17,-0.14)$^*$ & -52.95(-57.92,-47.98)$^*$ & -36.16(-39.18,-33.14)$^*$ & -16.79(-18.82,-14.76)$^*$ & -15.05(-16.34,-13.75)$^*$ & -1.82(-2,-1.63)$^*$\\
Staff priority & -42.09(-45.62,-38.55)$^*$ & -0.16(-0.18,-0.15)$^*$ & -56.14(-61.02,-51.27)$^*$ & -32.45(-35.41,-29.48)$^*$ & -23.7(-25.69,-21.71)$^*$ & -13.66(-14.93,-12.39)$^*$ & -1.7(-1.88,-1.52)$^*$\\
%-----------------------------------------------------------------
\rowcolor{gray!8} 
\multicolumn{8}{l}{Vaccine effect}\\
%-------------------------------------------------------------------
Different age-specific vaccine efficacy [Pfizer]& -1.12(-4.41,2.17)$^*$ & 0(-0.01,0.01)$^*$ & -0.98(-4.1,2.13)$^*$ & -0.76(-2.65,1.14) & -0.23(-1.59,1.14)$^*$ & -0.32(-1.15,0.51) & -0.07(-0.19,0.06)\\
Different age-specific vaccine efficacy [Moderna] & 3.7(0.36,7.03)$^*$ & 0.01(0,0.02)$^*$ & 3.93(0.78,7.09)$^*$ & 1.37(-0.55,3.29) & 2.56(1.18,3.95)$^*$ & 0.58(-0.26,1.43) & 0.05(-0.08,0.17)\\
%-----------------------------------------------------------------
\hline
\end{tabular}
\end{adjustbox}
\label{tab:Table2}
\footnotesize{$^b$ Vaccine assumed for resident agents, $^c$ Vaccine assumed for staff agents}
\end{table}


# Description bivariate

\begin{table}[H]
\centering
\caption{Description of interventions and parameter values.}
\vspace{0.5cm}
%\begin{adjustbox}{width=1\textwidth}
\begin{tabular}{p{3.5cm} p{3.5cm} p{3.5cm} p{3.5cm}}
\hline
\centering Probability of Introduction \\
&Low  &Medium  & High\\
\hline 
\rowcolor{gray!10}  
\multicolumn{4}{c}{Testing Frequency}\\
\rowcolor{gray!10} 
\multicolumn{4}{c}{ ($\omega$ = Introduction probability)}\\ \cline{1-4}
       & $\omega=0.05$ &$\omega=0.10$ &$\omega=0.15$\\
       &               &              &\\
Testing Interval & 7 days & 7 days & 7 days\\
Testing Interval & 5 days & 5 days & 5 days\\
Testing Interval & 3 days & 3 days & 3 days\\
\cline{1-4} 
%------------------------------------------------------------------
\rowcolor{gray!10} 
\hline
\multicolumn{4}{c}{Vaccine Performance}\\
\rowcolor{gray!10} 
\multicolumn{4}{c}{($V_{r}OR$ = Odds ratio for the vaccine effect on residents, $V_{s}OR$= Odds ratios for the vaccine effect on staff)}\\ \cline{1-4}
        & $\omega=0.05$   &$\omega=0.10$  &$\omega=0.15$\\
        &                 &               &\\
Equal   &  $V_rOR=0.0493$ &$V_rOR=0.0493$ &$V_rOR=0.0493$\\    
        &  $V_sOR=0.0493$ &$V_sOR=0.0493$ &$V_sOR=0.0493$\\
        &                 &               &\\ 
Pfizer  &  $V_rOR=0.0619$ &$V_rOR=0.0619$ &$V_rOR=0.0619$\\
        &  $V_sOR=0.0434$ &$V_sOR=0.0434$ &$V_sOR=0.0434$\\
        &                 &               &\\
Moderna & $V_rOR=0.1357$  &$V_rOR=0.1357$ &$V_rOR=0.1357$\\   
        & $V_sOR=0.0441$  &$V_sOR=0.0441$ &$V_sOR=0.0441$\\
 \cline{1-4}
%------------------------------------------------------------------
\rowcolor{gray!10} 
\hline
\multicolumn{4}{c}{Vaccine Prioritization}\\
\rowcolor{gray!10} 
\multicolumn{4}{c}{($V_r\%$=Percentage of residents vaccinated, $V_s\%$=Percentage of staff vaccinated)}\\
\cline{1-4}
        & $\omega=0.05$   &$\omega=0.10$  &$\omega=0.15$\\
        &                 &               &\\
Equal   & $V_r\% =50\%$   &$V_r\% =50\%$  &$V_r\% =50\%$\\
        & $V_s\% =50\%$   &$V_s\% =50\%$  &$V_s\% =50\%$\\
        &                 &               &\\
Staff Priority & $V_r\% =30\%$   &$V_r\% =30\%$  &$V_r\% =30\%$\\
        & $V_s\% =70\%$   &$V_s\% =70\%$  &$V_s\% =70\%$\\
        &                 &               & \\
Resident priority & $V_r\% =70\%$   &$V_r\% =70\%$  &$V_r\% =70\%$\\    
        & $V_s\% =30\%$   &$V_s\% =30\%$  &$V_s\% =30\%$\\
\cline{1-4}
%-----------------------------------------------------------------
\end{tabular}
%\end{adjustbox}
\label{tab:scenarios}
\end{table}


# Bivariate

## median and CIs

\begin{table}[H]
\centering
\caption{Results from scenario modeling using the median and 95\% confidence intervals.}
\vspace{0.5cm}
\begin{adjustbox}{width=1\textwidth}
\begin{tabular}{llllllll}
\hline
Scenario& Days to eradication& Attack Rate & 
Total Infected & Infected residents &  Infected staff & Hospitalizations& Deaths\\
%------------------------------------------------------------------
\hline
\rowcolor{gray!8} 
\multicolumn{8}{c}{Introduction Probability \& Testing Frequency}\\
\hline 
%------------------------------------------------------------------
High \& 7-days&	69.99 (0, 145.85) & 0.1 (0, 0.33) & 34.42 (0, 112.5) & 18.73 (0, 60.65) & 15.68 (0, 68) & 7.52 (0, 26.1) & 3.8 (0, 16)\\
High \& 5-days&	58.93 (0, 132.89) & 0.07 (0, 0.3) & 24.98 (0, 102.45) & 13.92 (0, 53.05) & 11.06 (0, 42.8) & 5.92 (0, 21) & 2.38 (0, 9.8)\\
High \& 3-days&	49.1 (0, 131.76) & 0.07 (0, 0.33) & 24.3 (0, 113.25) & 13.32 (0, 55.5) & 10.98 (0, 56) & 5.47 (0, 17.75) & 1.88 (0, 8)\\
Moderate \& 7-days&	43.34 (0, 125.78) & 0.05 (0, 0.19) & 16.72 (0, 64.4) & 8.18 (0, 29.6) & 8.54 (0, 38) & 3.58 (0, 13) & 1.61 (0, 4.8)\\
Moderate \& 5-days&		39.89 (0, 122.13) & 0.06 (0, 0.23) & 18.95 (0, 80) & 10.06 (0, 45.4) & 8.89 (0, 45) & 4.66 (0, 18.6) & 2.28 (0, 8)\\
Moderate \& 3-days&	31 (0, 89.61) &0.02 (0, 0.09) & 7.52 (0, 30.9) & 3.64 (0, 15.4) & 3.88 (0, 11.7) & 2.15 (0, 8.4) & 1.13 (0, 4)\\
Low \& 7-days&		12.24 (0, 76.16) & 0.02 (0, 0.15) & 5.73 (0, 50.3) & 3.46 (0, 31) & 2.27 (0, 17.1) & 1.75 (0, 7.7) & 0.81 (0, 4.4)\\
Low \& 5-days&	11.9 (0, 88.49) & 0.01 (0, 0.07) & 4.03 (0, 22.5) & 1.86 (0, 12) & 2.17 (0, 11.25) & 1.03 (0, 5.25) & 0.11 (0, 0)\\
Low \& 3-days&	9.42 (0, 38.53) & 0.01 (0, 0.05) & 3.03 (0, 17.25) & 1.41 (0, 9) & 1.62 (0, 8.55) & 1.17 (0, 4) & 0.56 (0, 4)\\
%------------------------------------------------------------------
\hline
\rowcolor{gray!8} 
\multicolumn{8}{c}{Introduction Probability \& Vaccine Prioritization}\\
\hline
%------------------------------------------------------------------
High \& Equal distribution & 61.94 (0, 142.98) &	0.08 (0, 0.32) & 26.67 (0, 110.45) & 15.24 (0, 63.65) & 11.43 (0, 46.2) & 5.93 (0, 22.05) & 2.76 (0, 12)\\
High \& Resident& 		59.52 (0, 145.83) &	0.09 (0, 0.33) & 32.56 (0, 114) & 13.62 (0, 49) & 18.93 (0, 68) & 5.72 (0, 17) & 2.16 (0, 12)\\
High \& Staff& 55.62 (0, 137.82) &	0.07 (0, 0.26) & 24.32 (0, 88.5) & 17.15 (0, 61.3) & 7.17 (0, 27.2) & 7.24 (0.9, 21.3) & 3.12 (0, 12)\\
Moderate \& Equal distribution& 40.32 (0, 121.33) & 0.05 (0, 0.21) & 16.7 (0, 71.8) & 9.16 (0, 41.4) & 7.54 (0, 33.2) & 4.2 (0, 17) & 2.14 (0, 8)\\
Moderate \& Resident& 42.58 (0, 125.5) &0.05 (0, 0.21) & 18.25 (0, 71) & 7.27 (0, 29.5) & 10.98 (0, 45.1) & 3.41 (0, 13.1) & 1.49 (0, 8)\\
Moderate \& Staff& 	30.25 (0, 95.54) &0.02 (0, 0.07) & 7.54 (0, 24) & 4.97 (0, 17) & 2.57 (0, 9) & 2.62 (0, 11) & 1.31 (0, 4)\\
Low \& Equal distribution& 11.52 (0, 87.12) & 0.01 (0, 0.13) & 4.89 (0, 45) & 2.52 (0, 21) & 2.36 (0, 24) & 1.38 (0, 6) & 0.59 (0, 4)\\
Low \& Resident& 	9.59 (0, 42.14) &	0.01 (0, 0.04) & 2.3 (0, 14.2) & 0.88 (0, 9) & 1.42 (0, 7.1) & 1.17 (0, 5.1) & 0.47 (0, 4)\\
Low \& Staff& 12.32 (0, 89.17) & 0.02 (0, 0.15) & 6.34 (0, 51.55) & 4.05 (0, 33.7) & 2.29 (0, 17.15) & 1.61 (0, 7.5) & 0.63 (0, 1.2)\\
%------------------------------------------------------------------
\hline
\rowcolor{gray!8} 
\multicolumn{8}{c}{Introduction Probability \& Vaccine Performance}\\
\hline
%------------------------------------------------------------------
High \& Similar efficacy& 62.24 (0, 141.6) & 0.08 (0, 0.27) & 28.41 (0, 94) & 15.69 (0, 53) & 12.73 (0, 52.5) & 6.43 (0, 17.5) & 2.35 (0, 8)\\
High \& Reduced efficacy (Pfizer)& 	41.57 (0, 129.53) & 0.05 (0, 0.23) & 17.54 (0, 80.75) & 10.3 (0, 51) & 7.23 (0, 28.25) & 4.57 (0, 16.75) & 2.29 (0, 12)\\
High \& Reduced efficacy (Moderna)& 	70.46 (0, 143.96) & 0.1 (0, 0.36) & 35.73 (1, 123.5) & 19.01 (0, 75) & 16.72 (0, 68) & 7.55 (0, 28) & 3.21 (0, 12)\\
Moderate \& Similar efficacy& 35.22 (0, 101.03) & 0.04 (0, 0.21) & 13.64 (0, 70.9) & 7.13 (0, 36.9) & 6.51 (0, 34) & 3.6 (0, 15.6) & 1.96 (0, 8)\\
Moderate \& Reduced efficacy (Pfizer)& 37.01 (0, 123.69) & 0.04 (0, 0.19) & 13.69 (0, 66.1) & 6.82 (0, 32.5) & 6.87 (0, 36.5) & 3.28 (0, 13.7) & 1.61 (0, 8)\\
Moderate \& Reduced efficacy (Moderna)& 40.64 (0, 124.1) & 0.04 (0, 0.19) & 15.25 (0, 63.7) & 7.69 (0, 27.4) & 7.57 (0, 40.8) & 3.48 (0, 12.7) & 1.49 (0, 8)\\
Low \& Similar efficacy& 10.18 (0, 71.08) & 0.01 (0, 0.07) & 4.42 (0, 24.4) & 2.47 (0, 10.8) & 1.96 (0, 13.8) & 1.47 (0, 7.6) & 0.44 (0, 4)\\
Low \& Reduced efficacy (Pfizer)& 12.06 (0, 71.23) & 0.01 (0, 0.05) & 4.66 (0, 17.85) & 2.63 (0, 10.9) & 2.03 (0, 8.85) & 1.52 (0, 6.85) & 0.9 (0, 4)\\
Low \& Reduced efficacy (Moderna)& 10.39 (0, 44.31) & 0.01 (0, 0.05) & 3.63 (0, 16.25) & 1.67 (0, 9) & 1.96 (0, 8.35) & 1.06 (0, 5.45) & 0.23 (0, 1.8)\\
%------------------------------------------------------------------
\hline
\end{tabular}
\end{adjustbox}
\label{tab:ScenarioModeling}
\end{table}

## Differences

\begin{table}[H]
\centering
\caption{Results from scenario modeling using the median and 95\% confidence intervals.}
\vspace{0.5cm}
\begin{adjustbox}{width=1\textwidth}
\begin{tabular}{llllllll}
\hline
Scenario& Days to eradication& Attack Rate & 
Total Infected & Infected residents &  Infected staff & Hospitalizations& Deaths\\
%------------------------------------------------------------------
\hline
\rowcolor{gray!8} 
\multicolumn{8}{c}{Introduction Probability \& Testing Frequency}\\
\hline 
%------------------------------------------------------------------
High \& 5-days&	-1.14(-6.47,4.18)$^*$ & -0.11(-0.14,-0.08)$^*$ & -37.71(-46.47,-28.95)$^*$ & -23.56(-29.28,-17.83)$^*$ & -14.15(-17.38,-10.92)$^*$ & -9.75(-12.22,-7.29)$^*$ & -1.34(-1.7,-0.97)$^*$\\
High \& 3-days&	-22.99(-28.37,-17.62)$^*$ & -0.2(-0.22,-0.17)$^*$ & -68.26(-77.11,-59.42)$^*$ & -42.56(-48.34,-36.78)$^*$ & -25.7(-28.97,-22.44)$^*$ & -17.94(-20.43,-15.45)$^*$ & -2.33(-2.69,-1.96)$^*$\\
Moderate \& 5-days&		39.89 (0, 122.13) & 0.06 (0, 0.23) & 18.95 (0, 80) & 10.06 (0, 45.4) & 8.89 (0, 45) & 4.66 (0, 18.6) & 2.28 (0, 8)\\
Moderate \& 3-days&	-32.96(-37.9,-28.03)$^*$ & -0.15(-0.17,-0.13)$^*$ & -51.05(-56.98,-45.11)$^*$ & -30.68(-34.34,-27.02)$^*$ & -20.36(-22.74,-17.99)$^*$ & -13.07(-14.66,-11.48)$^*$ & -1.57(-1.79,-1.35)$^*$\\
Low \& 5-days&	-22.49(-28.9,-16.07)$^*$ & -0.13(-0.15,-0.1)$^*$ & -43.49(-53.21,-33.77)$^*$ & -23.43(-28.93,-17.94)$^*$ & -20.06(-24.37,-15.75)$^*$ & -9.99(-12.27,-7.71)$^*$ & -1.23(-1.54,-0.93)$^*$\\
Low \& 3-days&	-31.51(-37.71,-25.31)$^*$ & -0.16(-0.18,-0.13)$^*$ & -54.02(-63.42,-44.63)$^*$ & -29.41(-34.71,-24.1)$^*$ & -24.62(-28.78,-20.45)$^*$ & -12.37(-14.57,-10.16)$^*$ & -1.54(-1.83,-1.24)$^*$\\
%------------------------------------------------------------------
\hline
\rowcolor{gray!8} 
\multicolumn{8}{c}{Introduction Probability \& Vaccine Prioritization}\\
\hline
%------------------------------------------------------------------
High \& Resident&2.01(-3.61,7.62)$^*$ & -0.01(-0.03,0.01) & -3.26(-10.11,3.59) & -6.79(-11.16,-2.43)$^*$ & 3.53(0.81,6.24)$^*$ & -3.27(-5.18,-1.35)$^*$ & -0.5(-0.79,-0.2)$^*$\\
High \& Staff& -5.1(-10.6,0.4)$^*$ & -0.02(-0.04,0) & -6.18(-12.89,0.52) & -0.71(-4.99,3.57)$^*$ & -5.47(-8.13,-2.82)$^*$ & -0.81(-2.68,1.07)$^*$ & -0.19(-0.49,0.1)$^*$\\
Moderate \& Resident& 6.37(1.41,11.32)$^*$ & 0(-0.01,0.01) & 0.15(-4.3,4.59) & -2.84(-5.51,-0.17)$^*$ & 2.98(1.06,4.91)$^*$ & -1.14(-2.31,0.04)$^*$ & -0.21(-0.38,-0.03)\\
Moderate \& Staff& 	-2(-6.89,2.9)$^*$ & 0(-0.02,0.01) & -1.19(-5.58,3.2) & 2.02(-0.62,4.66)$^*$ & -3.21(-5.12,-1.31)$^*$ & 0.74(-0.42,1.9)$^*$ & -0.05(-0.22,0.12)\\
Low \& Resident& 	1.96(-3.52,7.45)$^*$ & 0.01(0,0.03)$^*$ & 3.97(-0.8,8.75)$^*$ & 0(-2.45,2.45) & 3.98(1.49,6.46)$^*$ & 0(-1.06,1.06) & 0.16(0,0.32)\\
Low \& Staff& -6.36(-11.74,-0.99)$^*$ & -0.01(-0.02,0)$^*$ & -3.09(-7.77,1.59)$^*$ & -1.05(-3.45,1.35) & -2.04(-4.48,0.4)$^*$ & -0.72(-1.77,0.32) & 0.01(-0.15,0.16)\\
%------------------------------------------------------------------
\hline
\end{tabular}
\end{adjustbox}
\label{tab:ScenarioModeling}
\end{table}

