---
title: "Simulation Outputs"
output: html_notebook
---

# Setup

```{r}
### Libraries
library(dplyr); library(ggplot2); library(ggpubr)
#Total population
N <- 170 + 174
# ==============================================================================
# FUNCTIONS
# ==============================================================================
# Read Simulations
# ------------------------------------------------------------------------------
ReadSims <- function(dir){
  # dir = paste0(p, "00/EC/")
  f <- list.files(dir, full.names = TRUE)
  L <- lapply(1:length(f), function(x){
    read.csv(f[x], fileEncoding = 'UTF-8') %>% # read files
      mutate(Sim = x, day = ceiling(cycle/24)) %>% # create variable for sim number and day
      group_by(Sim, day) %>% # group by simulation and day
      summarise_all(.funs = max) %>%# get the max for all the records.
      ungroup()
    })
  
  N_sim <- lapply(L, nrow) %>% unlist() %>% max(.)
  
  L <- lapply(L, function(x){
    d <- N_sim - nrow(x)
      x %>%
        slice(c(1:nrow(.), rep(nrow(.), each = d))) %>%
        mutate(day = 1:n())
  })
  L %>%
    do.call(rbind, .)
}
# Functions for getting quantiles
# ------------------------------------------------------------------------------
Q05 <- function(sims) quantile(sims, 0.05)
Q25 <- function(sims) quantile(sims, 0.25)
Q75 <- function(sims) quantile(sims, 0.75)
Q95 <- function(sims) quantile(sims, 0.95)

# Function for summarizing the cycles
# ------------------------------------------------------------------------------
CycleSums <- function(sims){
  # sims = D00
  cycle_IQR <- sims %>%
    dplyr::select(-Sim) %>%
    group_by(day) %>%
    summarise_all(.funs = c(Median = median, Q25 = Q25, Q75 = Q75))
  
  cycle_TTE <- sims %>%
    group_by(Sim) %>%
    filter(I == max(I)) %>%
    filter(cycle == max(cycle)) %>%
    mutate(day = floor(cycle/24),
           Cumulative_I = Cumulative_I_r + Cumulative_I_s,
           InfectionRate = Cumulative_I/N) %>%
    distinct()
  
  return(list(cycle_IQR = cycle_IQR, cycle_TTE = cycle_TTE))
}

# Function for the plots
# ------------------------------------------------------------------------------
PlotCycles <- function(sims, var, col, y_lim){
  # sims = D00; var = "I"; col = "red3"
  # y_lab = ifelse(grepl("_P", var), "Infected \n pig herds", "Infected \n wild boar")
  p = sims %>%
    CycleSums() %>%
    .$cycle_IQR %>%
    ggplot(aes(x = day)) +
    geom_line(aes(y = eval(parse(text = paste0(var, '_Median')))),
      col = col, lwd = 1) +
    geom_ribbon(aes(
      ymin = eval(parse(text = paste0(var, '_Q25'))),
      ymax = eval(parse(text = paste0(var, '_Q75')))),
      alpha = 0.3, fill = col) +
    ylab("Number of Infected") +
    theme_minimal() 
    # ylab(y_lab) +
  #   xlab("Days") +
  #   theme(legend.position = "none",
  #     axis.title.y = element_text(angle = 0, vjust = 0.5))
  # if( !missing(y_lim) ) p = p + ylim(y_lim)
  p
  
}
#### Function for time to eradication ####
#----------------------------------------#
TE_data <- function(data){
  data %>%
    mutate(day = floor(cycle/24)) %>%
    group_by(Sim, day) %>%
    summarise(I = max(I)) %>%
    group_by(Sim) %>%
    filter(I == max(I)) %>%
    filter(day == min(day))
}

#### Plot the outputs ####
#-------------------------------#
Plots <- function(x, main = ''){
  ##### NUMBER OF INFECTED ####
  CumI_p <- x %>%
  ggplot() +
  geom_boxplot(aes(y = InfectionRate, fill = Scenario), alpha = 0.6) +
  scale_fill_manual(values = ColPal) +
  ylab("Infection rate") +
  ggtitle("Epidemic Size") +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  ##### EPIDEMIC LENGTH ####
  EpiL_p <- x %>% 
    ggplot() +
  geom_histogram(aes(day, fill = Scenario, col = Scenario), alpha = 0.4, binwidth = 5) +
  scale_fill_manual(values = ColPal) +
    scale_color_manual(values = ColPal) +
  facet_grid(~Scenario) +
  ggtitle(" Epidemic duration") +
    theme_minimal()

  if(length(unique(x$Scenario)) == 1){
    ggarrange(CumI_p, EpiL_p, ncol = 2, common.legend = T) %>%
      annotate_figure(text_grob(main, color = "grey20", face = "bold", size = 14)) 
  }else{
    ggarrange(CumI_p, EpiL_p, nrow = 2, common.legend = T) %>%
      annotate_figure(text_grob(main, color = "grey20", face = "bold", size = 14)) 
  }
}

#### Summary table ####
#-------------------------------#
Sum_Tbl <- function(x){
  x %>%
    group_by(Scenario) %>%
    summarise_at(.vars = c('InfectionRate', 'day', 'Cumulative_I', 'Cumulative_I_r', 'Cumulative_I_s', 'Cumulative_H', 'D'), .funs = c(m = median, Q05 = Q05, Q95 = Q95)) %>%
    mutate(across(where(is.numeric), ~round(., 2)),
           InfectionRate = paste0(InfectionRate_m, ' (', InfectionRate_Q05, ',', InfectionRate_Q95, ')'),
           day = paste0(day_m, ' (', day_Q05, ',', day_Q95, ')'),
           Cumulative_I = paste0(Cumulative_I_m, ' (', Cumulative_I_Q05, ',', Cumulative_I_Q95, ')'),
           Cumulative_I_r = paste0(Cumulative_I_r_m, ' (', Cumulative_I_r_Q05, ',', Cumulative_I_r_Q95, ')'),
           Cumulative_I_s = paste0(Cumulative_I_s_m, ' (', Cumulative_I_s_Q05, ',', Cumulative_I_s_Q95, ')'),
           Cumulative_H = paste0(Cumulative_H_m, ' (', Cumulative_H_Q05, ',', Cumulative_H_Q95, ')'),
           Cumulative_D = paste0(D_m, ' (', D_Q05, ',', D_Q95, ')')) %>%
    select(Scenario, day, InfectionRate, Cumulative_I, Cumulative_I_r, Cumulative_I_s, Cumulative_H, Cumulative_D)
}
```


# Test
```{r Test}
p <- "../../Data/SimsOut/Test/"
ColPal <- c("grey40")
### Test
Bb <- ReadSims(p)
Sb <- PlotCycles(Bb, var = "I", col = "red3")
Ib <- CycleSums(Bb) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Baseline')

BTbl <- Sum_Tbl(Ib)
Plots(Ib, 'Baseline Scenario')
Sb
BTbl
```


# Baseline

```{r}
p <- "../../Data/SimsOut/Baseline/"
ColPal <- c("grey40")
### Baseline
Bb <- ReadSims(p)
BIp <- PlotCycles(Bb, var = "I", col = "red3")
BCIp <- Bb %>%
  mutate(CumI = Cumulative_I_r + Cumulative_I_s) %>% 
  PlotCycles(., var = 'CumI', col = 'red3')

Ib <- CycleSums(Bb) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Baseline')

BTbl <- Sum_Tbl(Ib)
Plots(Ib, 'Baseline Scenario') %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/Baseline.png", width = 8, height = 4)
BIp; BCIp
BTbl
```



# Sensitivity analysis
## Transmission probability

00 - 0.50
01 - 0.52
02 - 0.55

```{r Transmission}
p <- "../../Data/SimsOut/SensitivityAnalysis/TransmissionProbability/"
ColPal <- c("#B284E3", "grey40", "#F28C8C")
### 3% Transmission Probability
D00 <- ReadSims(paste0(p, "Low/"))
S00 <- PlotCycles(D00, var = "I", col = "red3")
I00 <- CycleSums(D00) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Low transmission')
### 7% Introduction Probability
D01 <- ReadSims(paste0(p, "High/"))
S01 <- PlotCycles(D01, var = "I", col = "red3")
I01 <- CycleSums(D01) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'High transmission')
# ### 10% Introduction Probability
# D02 <- ReadSims(paste0(p, "02/"))
# S02 <- PlotCycles(D02, var = "I", col = "red3")
# I02 <- CycleSums(D02) %>%
#   .$cycle_TTE %>%
#   mutate(Scenario = 'High transmission')

x <- rbind(I00, Ib, I01) %>%
  mutate(Scenario = factor(Scenario, levels = c('Low transmission', 'Baseline', 'High transmission'))) 

TTbl <- Sum_Tbl(x)
x %>%
  Plots('Transmission Probability') %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/Transmission.png", width = 9, height = 5)
TTbl
```


## Introduction probability

00 - 0.05
01 - 0.1
02 - 0.15

```{r Introduction}
p <- "../../Data/SimsOut/SensitivityAnalysis/IntroductionProbability/"
ColPal <- c("#704500", 'grey40', "#076600")
### 1% Introduction Probability
D00 <- ReadSims(paste0(p, "Low/"))
S00 <- PlotCycles(D00, var = "I", col = "red3")
I00 <- CycleSums(D00) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Low Introduction Probability')
### 10% Introduction Probability
D01 <- ReadSims(paste0(p, "High/"))
S01 <- PlotCycles(D01, var = "I", col = "red3")
I01 <- CycleSums(D01) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'High Introduction Probability')
### 10% Introduction Probability
# D02 <- ReadSims(paste0(p, "02/"))
# S02 <- PlotCycles(D02, var = "I", col = "red3")
# I02 <- CycleSums(D02) %>%
#   .$cycle_TTE %>%
#   mutate(Scenario = '10% Introduction Probability')

x <- rbind(I00, Ib, I01) %>%
  mutate(Scenario = factor(Scenario, levels = c('Low Introduction Probability', 'Baseline', 'High Introduction Probability'))) 

ITbl <- Sum_Tbl(x)

x %>%
  Plots(main = "Probability of Introduction")  %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/Introduction.png", width = 9, height = 5)
ITbl
```

## Detection probability

00 - 75% detection probability
01 - 80% detection probability
02 - 90% Detection probability

```{r DetectionProbability SA}
p <- "../../Data/SimsOut/SensitivityAnalysis/DetectionProbability/"
ColPal <- c("#00827E", 'grey40', "#00CFB7")
### 75% Detection Probability
D00 <- ReadSims(paste0(p, "Low/"))
S00 <- PlotCycles(D00, var = "I", col = "red3")
I00 <- CycleSums(D00) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Low Detection Probability')
## 85% Detection Probability
D01 <- ReadSims(paste0(p, "High/"))
S01 <- PlotCycles(D01, var = "I", col = "red3")
I01 <- CycleSums(D01) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'High Detection Probability')


x <- rbind(I00, Ib, I01) %>%
  mutate(Scenario = factor(Scenario, levels = c('Low Detection Probability', 'Baseline', 'High Detection Probability')))

DTbl <- Sum_Tbl(x)
x %>%
  Plots(main = "Probability of Detection") %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/ProbDetection.png", width = 9, height = 5)
DTbl
```


## PPE Effect

00 - LB
01 - Estimate
02 - UB (0.2408)

```{r FaceMasks}
p <- "../../Data/SimsOut/SensitivityAnalysis/FaceMasks/"
ColPal <- c("#5C9669", "#6A918C", "#7280B3")
### 1% Introduction Probability
D00 <- ReadSims(paste0(p, "High/"))
S00 <- PlotCycles(D00, var = "I", col = "red3")
I00 <- CycleSums(D00) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'High effect PPE')
### 5% Introduction Probability
D01 <- ReadSims(paste0(p, "Low/"))
S01 <- PlotCycles(D01, var = "I", col = "red3")
I01 <- CycleSums(D01) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Low effect PPE')

x <- rbind(I00, Ib, I01) %>%
  mutate(Scenario = factor(Scenario, levels = c('High effect PPE', 'Baseline', 'Low effect PPE'))) 

PPETbl <- Sum_Tbl(x)
x %>% 
  Plots('Effect of PPE') %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/PPE.png", width = 9, height = 5)
PPETbl
```


## Testing Frequency ()

```{r}
p <- "../../Data/SimsOut/SensitivityAnalysis/TestingFreq/"
ColPal <- c("#5C9669", "#6A918C", "#7280B3")
### 1% Introduction Probability
D00 <- ReadSims(paste0(p, "Testing5/"))
S00 <- PlotCycles(D00, var = "I", col = "red3")
I00 <- CycleSums(D00) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Every 5 days')
### 5% Introduction Probability
D01 <- ReadSims(paste0(p, "Testing3/"))
S01 <- PlotCycles(D01, var = "I", col = "red3")
I01 <- CycleSums(D01) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Every 3 days')

x <- rbind(I00, Ib, I01) %>%
  mutate(Scenario = factor(Scenario, levels = c('Baseline', 'Every 5 days', 'Every 3 days'))) 

TFTbl <- Sum_Tbl(x)
TFTbl
x %>% 
  Plots('Testing Frequency') %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/TestingFreq.png", width = 9, height = 5)
```


## Vaccine Effect

```{r}
p <- "../../Data/SimsOut/SensitivityAnalysis/VaccineEffect/"

ColPal <- c("#5C9669", "#6A918C", "#7280B3")
### Same vaccine effect for residents and staff
D00 <- ReadSims(paste0(p, "Equal/"))
S00 <- PlotCycles(D00, var = "I", col = "red3")
I00 <- CycleSums(D00) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Same vaccine effect')
### Different vaccine effect for residents and staff (Pfizer)
D01 <- ReadSims(paste0(p, "Pfizer/"))
S01 <- PlotCycles(D01, var = "I", col = "red3")
I01 <- CycleSums(D01) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Pfizer')
### Different vaccine effect for residents and staff (Pfizer)
D02 <- ReadSims(paste0(p, "Moderna/"))
S02 <- PlotCycles(D02, var = "I", col = "red3")
I02 <- CycleSums(D02) %>%
  .$cycle_TTE %>%
  mutate(Scenario = 'Moderna')

x <- rbind(I00, I01, I02) %>%
  mutate(Scenario = factor(Scenario, levels = c('Same vaccine effect', 'Pfizer', 'Moderna'))) 

VeTbl <- Sum_Tbl(x)

x %>%
  Plots('Vaccine Effect') %>%
  ggsave(filename = "../../Documentation/Figures/SensitivityAnalysis/VaccinationEf.png", width = 9, height = 5)
VeTbl
```


### Summary 

```{r SA Summary}
rbind(BTbl, TTbl, ITbl, DTbl, PPETbl, TFTbl, VeTbl) %>%
  distinct() %>%
write.csv(., "../../Documentation/Tables/SA_sum.csv", row.names = F)
```




# Scenario Modeling

## Function for plots
```{r}
PlotScenarios <- function(x, v, main){
  CumI_p <- x %>%
  ggplot() +
  geom_boxplot(aes(y = InfectionRate, fill = eval(parse(text=v))), alpha = 0.6) +
  scale_fill_manual(values = ColPal) +
  facet_wrap(~cl) +
  theme_minimal()+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.background = element_rect(colour="black",
                                        fill="grey90")) +
    ylab("Proportion of Infected") +
    labs(fill = v)

  EpiL_p <- x %>%
    ggplot() +
    geom_histogram(aes(day, fill = eval(parse(text=v)), color = eval(parse(text=v))),
                   alpha = 0.6,
                   binwidth = 5) +
    scale_fill_manual(values = ColPal) +
    scale_color_manual(values = ColPal) +
    facet_wrap( ~ cl + eval(parse(text=v)), nrow = 1) +
    ggtitle(" Epidemic duration") +
    theme_minimal() +
    theme(strip.background = element_blank(), strip.text = element_blank()) +
    labs(fill = v)
  
  ggarrange(CumI_p, EpiL_p, nrow = 2, common.legend = T) %>%
    annotate_figure(text_grob(
      main,
      color = "grey20",
      face = "bold",
      size = 14
    ))
}

```


## Testing Frequency

```{r}
ColPal <- c("#C70704", "#BAB700", "#008C0C")
p <- "../../Data/SimsOut/Scenarios/TF/"
d <- list.files(p)
DL <- lapply(paste0(p,d), function(x){
  D <- ReadSims(x) %>%
    CycleSums(.) %>%
    .$cycle_TTE %>%
    mutate(Scenario = factor(gsub(p, '', x), levels = c('HI_7', 'HI_5', 'HI_3', 'MI_7', 'MI_5', 'MI_3', 'LI_7', 'LI_5', 'LI_3')))
}) %>%
  do.call(rbind,.) %>% 
  mutate(cl = factor(gsub('_.*', '', Scenario), levels = c('HI', 'MI', 'LI')),
         cl = recode(cl, HI = 'High', MI = 'Medium', LI = 'Low'),
    TestingInterval = factor(gsub('.*_', '', Scenario), levels = c('7', '5', '3')),
    TestingInterval = recode(TestingInterval, `7` = '7 Days', `5` = '5 Days', `3` = '3 Days'))


PlotScenarios(x = DL, v = 'TestingInterval', main = "Testing Interval") %>%
  ggsave(filename = "../../Documentation/Figures/Scenarios/TF.png", width = 9, height = 6)
Sum_Tbl(DL)  %>%
  write.csv(., "../../Documentation/Tables/TF.csv", row.names = F)
```


## Vaccine Effect

```{r}
ColPal <- c("#5C9669", "#6A918C", "#7280B3")
p <- "../../Data/SimsOut/Scenarios/VE/"
d <- list.files(p)
DL <- lapply(paste0(p,d), function(x){
  D <- ReadSims(x) %>%
    CycleSums(.) %>%
    .$cycle_TTE %>%
    mutate(Scenario = factor(gsub(p, '', x), levels = c('HI_E', 'HI_P', 'HI_M', 'MI_E', 'MI_P', 'MI_M', 'LI_E', 'LI_P', 'LI_M')))
}) %>%
  do.call(rbind,.) %>% 
  mutate(cl = factor(gsub('_.*', '', Scenario), levels = c('HI', 'MI', 'LI')),
         cl = recode(cl, HI = 'High', MI = 'Medium', LI = 'Low'),
    VaccineEffect = factor(gsub('.*_', '', Scenario), levels = c('E', 'P', 'M')))


PlotScenarios(x = DL, v = 'VaccineEffect', main = "Vaccine Effect") %>%
  ggsave(filename = "../../Documentation/Figures/Scenarios/VE.png", width = 9, height = 6)
Sum_Tbl(DL) %>%
  write.csv(., "../../Documentation/Tables/VE.csv", row.names = F)
```

## Vaccine Distribution

```{r}
ColPal <- c("#414042", "#8C8700", "#5D0DB3")
p <- "../../Data/SimsOut/Scenarios/VD/"
d <- list.files(p)
DL <- lapply(paste0(p,d), function(x){
  D <- ReadSims(x) %>%
    CycleSums(.) %>%
    .$cycle_TTE %>%
    mutate(Scenario = factor(gsub(p, '', x), levels = c('HI_E', 'HI_R', 'HI_S', 'MI_E', 'MI_R', 'MI_S', 'LI_E', 'LI_R', 'LI_S')))
}) %>%
  do.call(rbind,.) %>% 
  mutate(cl = factor(gsub('_.*', '', Scenario), levels = c('HI', 'MI', 'LI')),
         cl = recode(cl, HI = 'High', MI = 'Medium', LI = 'Low'),
    VaccineDistribution = factor(gsub('.*_', '', Scenario), levels = c('E', 'R', 'S')),
    VaccineDistribution = recode(VaccineDistribution, E = 'Equal Distribution', R = 'Resident Priority', S = 'Staff Priority'))

PlotScenarios(x = DL, v = 'VaccineDistribution', main = "Vaccine Distribution") %>%
  ggsave(filename = "../../Documentation/Figures/Scenarios/VD.png", width = 9, height = 6)
Sum_Tbl(DL) %>%
  write.csv(., "../../Documentation/Tables/VD.csv", row.names = F)
```

```{r}
Sum_Tbl(DL)
```