---
title: "Tables"
output:
  word_document: default
  html_notebook: default
---

# Parameters table

## Population characteristics

|Variable             |Distribution                                                             |
|---------------------|-------------------------------------------------------------------------|
|Work Schedule        |$Multinom \sim (X_{morning} = 0.4, X_{Afternoon} = 0.4, X_{Night} = 0.2)$|
|Staff type           |$Multinom \sim (X_{CN} = 0.6, X_{RN} = 0.15, X_{LPN} = 0.15)$            |
|CN contacts per hour |$Multinom \sim (X_0 = 0.7, X_1 = 0.3)$                                   |
|RN contacts per hour |$Multinom \sim (X_0 = 0.25, X_1 = 0.75)$                                 |
|LPN contacts per hour|$Multinom \sim (X_0 = 0.15, X_2 = 0.2, X_3 = 0.25, X_4 = 0.2, X_5 = 0.2)$|


## Infection

| Name                                                         | Value            | Reference|
|--------------------------------------------------------------|------------------|----------|
| Latent period ($\alpha$)                                     | $Lognormal(7, 3)$| [@He2020]$^{b,c}$|
| Asymptomatic ($f$)                                           | $0.25$           | [@Feaster2020]   |
| Average recovery time ($\gamma_1$)                           | $15 days$        | |
| Proportion of Hospitalizations ($\sigma_1$)                  | $0.23$           |          |
|Median number of days from symptom onset to hosp ($\gamma_2$) | $4(1,9)$         | [@CDC2020]|
|Median number of days of hosp for ICU admission ($\gamma_3$)   | $6(3,10)$       | [@CDC2020]|
|Median number of days of hosp for non ICU admission ($\gamma_3$)| $12(6,20)$     | [@CDC2020]|
|Percentage of deaths on hospitalization ($\sigma_2$)          | $11.8%$          |          |
| Shedding probability ($\psi_1$)                              | $0.41$           | $^a$     |
| Infection probability ($\psi_2$)                             | $0.41$           | $^a$     |
| Introduction probability ($\omega$)                          | $0.1$            | $^a$     |



## Interventions 

| Name                             | Value              | Reference|
|----------------------------------|--------------------|----------|
| Proportion of staff using PPE($PPE_S\%$)| 0.9                |$^a$|
| Proportion of residents using PPE($PPE_R\%$)| 0.75               |$^a$|
| PPE Effect ($OR_\pi$)            | 0.1467             |[@Chu2020]$^a$|
| Test detection probability($\phi$)| $80\%$             | $^a$     |
| Proportion of Staff tested       | $90\%$             | $^a$     |
| Proportion of Residents tested   | $33.3%$            | $^a$     |
| Frequency of testing             |   Weekly           | $^a$     |
| Vaccine effect ($OR_\upsilon$)   | 0.0493             | [@Baden2020]$^a$|
| Vaccine immunity duration        | $120\ days$        | $^a$         |


## Sensitivity analysis

| Scenario                    | Target parameter                   |Value used|
|-----------------------------|------------------------------------|----------|
|Low transmission             | Shedding and infection probability | 0.38     |
|High transmission            | Shedding and infection probability | 0.45     |
|Low Introduction Probability | Introduction probability           | 0.05     |
|High Introduction Probability| Introduction probability           | 0.15     |
| Low Detection Probability   | Detection probability              | 0.7      |
| High Detection Probability  | Detection probability              | 0.90     |
| High effect PPE             | PPE effect                         | 0.0722   |
| Low effect PPE              | PPE effect                         | 0.3408   |
| Every 5 days                | Testing frequency                  |every 5 days  |
| Every 3 days                | Testing frequency                  | every 3 days  |


